name: Deploy to Github Pages

on:
  push: 
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: action/checkout@v2

    - name: Setup Node.js
      uses: action/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build and Deploy
      run: |
          npm run build --base-href=/MyApp/
          npx angular-cli-ghpages --dir/MyApp
      env:
        CI: false
